name: Build and push Docker images

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Push docker images'
        required: false
        default: 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}

      # 2. Set up QEMU (for multi-arch builds, optional)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 3. Set up Docker Buildx (recommended for modern builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Build and push the images
      - name: Build and push images
        run: |
          docker compose build
          docker compose push